
import scroll from './modules/scroll';
import showHeaderPhone from './modules/header-phone';
import menuHandler from './modules/menu-handler';
import popupHandler from './modules/popup-handler';
import validate from './modules/validate';
import sendForm from './modules/send-form';
import faqAccordeon from './modules/faq-accordeon';
import loadDB from './modules/load-DB';
import advantagesPopup from './modules/advantages-popup';
import repairTypes from './modules/repair-types';
import documents from './modules/documents';
import portfolio from './modules/portfolio';
import reviews from './modules/reviews';
import services from './modules/services';

scroll();
showHeaderPhone();
menuHandler();
popupHandler();
validate();
sendForm();
faqAccordeon();
loadDB();
advantagesPopup();
repairTypes();
documents();
portfolio();
reviews();
services();
