
import scroll from './modules/scroll';
import showHeaderPhone from './modules/header-phone';
import menuHandler from './modules/menu-handler';
import popupRepair from './modules/popup-repair';
import popupConsult from './modules/popup-consult';
import validate from './modules/validate';
import sendForm from './modules/send-form';
import popupPrivacy from './modules/popup-privacy';
import faqAccordeon from './modules/faq-accordeon';
import loadDB from './modules/load-DB';
import advantagesPopup from './modules/advantages-popup';
import repairTypes from './modules/repair-types';
import documents from './modules/documents';
import portfolio from './modules/portfolio';

scroll();
showHeaderPhone();
menuHandler();
popupRepair();
popupConsult();
validate();
sendForm();
popupPrivacy();
faqAccordeon();
loadDB();
advantagesPopup();
repairTypes();
documents();
portfolio();
